from enum import Enum


class ProvisionType(str, Enum):
    REQUIREMENT = "REQUIREMENT"
    PROHIBITION = "PROHIBITION"
    DEFINITION = "DEFINITION"
    PROCEDURE = "PROCEDURE"
    ELIGIBILITY_CONDITION = "ELIGIBILITY_CONDITION"
    EXCEPTION = "EXCEPTION"
    TARIFF_RULE = "TARIFF_RULE"
    ORIGIN_RULE = "ORIGIN_RULE"
    LICENSING_RULE = "LICENSING_RULE"
    DOCUMENT_REQUIREMENT = "DOCUMENT_REQUIREMENT"
    PENALTY = "PENALTY"
    SCOPE = "SCOPE"
    REFERENCE = "REFERENCE"
    OTHER = "OTHER"
