from typing import Protocol

from packages.domain.source.artifacts import ExtractedText, SourceArtifact


class SourceArtifactRepository(Protocol):
    def add(self, artifact: SourceArtifact) -> None: ...
    def get(self, artifact_id: str) -> SourceArtifact | None: ...
    def list_for_document_version(self, document_version_id: str, limit: int | None = None) -> list[SourceArtifact]: ...


class ExtractedTextRepository(Protocol):
    def add(self, text: ExtractedText) -> None: ...
    def get(self, artifact_id: str) -> ExtractedText | None: ...
