from typing import Protocol

from packages.domain.source.authority_scope import AuthorityScopeAssignment


class AuthorityScopeRepository(Protocol):
    def add(self, assignment: AuthorityScopeAssignment) -> None: ...
    def get(self, assignment_id: str) -> AuthorityScopeAssignment | None: ...
    def list_for_authority(self, authority_id: str) -> list[AuthorityScopeAssignment]: ...
    def list_for_scope(self, jurisdiction_id: str, regulatory_domain_code: str, fact_type_code: str) -> list[AuthorityScopeAssignment]: ...
