from typing import Protocol

from packages.domain.source.authority_endpoint import AuthorityEndpoint


class AuthorityEndpointRepository(Protocol):
    def add(self, endpoint: AuthorityEndpoint) -> None: ...
    def get(self, endpoint_id: str) -> AuthorityEndpoint | None: ...
    def list_for_authority(self, authority_id: str) -> list[AuthorityEndpoint]: ...
