from typing import Protocol
from packages.domain.source.authority_registry import Authority


class AuthorityRepository(Protocol):
    def add(self, authority: Authority) -> None: ...
    def get(self, authority_id: str) -> Authority | None: ...
    def get_by_acronym(self, acronym: str) -> Authority | None: ...
    def list_for_jurisdiction(self, jurisdiction_id: str) -> list[Authority]: ...
