from typing import Protocol

from packages.domain.source.authority import Instrument, SourceAuthorityAssignment


class SourceAuthorityRepository(Protocol):
    def add(self, assignment: SourceAuthorityAssignment) -> None: ...
    def get(self, assignment_id: str) -> SourceAuthorityAssignment | None: ...
    def list_for_source(self, source_id: str) -> list[SourceAuthorityAssignment]: ...


class InstrumentRepository(Protocol):
    def add(self, instrument: Instrument) -> None: ...
    def get(self, instrument_id: str) -> Instrument | None: ...
    def get_for_document(self, document_id: str) -> Instrument | None: ...
