from typing import Protocol

from packages.domain.source.extraction import ExtractionRun, ExtractionSegment


class ExtractionRunRepository(Protocol):
    def add(self, extraction: ExtractionRun) -> None: ...
    def get(self, extraction_id: str) -> ExtractionRun | None: ...
    def list_for_artifact(self, artifact_id: str) -> list[ExtractionRun]: ...


class ExtractionSegmentRepository(Protocol):
    def add(self, segment: ExtractionSegment) -> None: ...
    def list_for_artifact(self, artifact_id: str) -> list[ExtractionSegment]: ...
    def list_for_extraction(self, extraction_id: str) -> list[ExtractionSegment]: ...
