from typing import Protocol

from packages.domain.source.extraction import ExtractionComparison, ExtractionRun, ExtractionSegment


class ExtractionRunRepository(Protocol):
    def add(self, extraction: ExtractionRun) -> None: ...
    def get(self, extraction_id: str) -> ExtractionRun | None: ...
    def list_for_artifact(self, artifact_id: str) -> list[ExtractionRun]: ...


class ExtractionSegmentRepository(Protocol):
    def add(self, segment: ExtractionSegment) -> None: ...
    def list_for_artifact(self, artifact_id: str) -> list[ExtractionSegment]: ...
    def list_for_extraction(self, extraction_id: str) -> list[ExtractionSegment]: ...


class ExtractionComparisonRepository(Protocol):
    def add(self, comparison: ExtractionComparison) -> None: ...
    def get(self, comparison_id: str) -> ExtractionComparison | None: ...
    def find(self, baseline_extraction_id: str, candidate_extraction_id: str) -> ExtractionComparison | None: ...
