from typing import Protocol

from packages.domain.source.extraction import ExtractionComparison, ExtractionRun, ExtractionSegment
from packages.domain.source.extraction_diff import ExtractionDiff, ExtractionDiffEntry


class ExtractionRunRepository(Protocol):
    def add(self, extraction: ExtractionRun) -> None: ...
    def get(self, extraction_id: str) -> ExtractionRun | None: ...
    def list_for_artifact(self, artifact_id: str, limit: int | None = None) -> list[ExtractionRun]: ...


class ExtractionSegmentRepository(Protocol):
    def add(self, segment: ExtractionSegment) -> None: ...
    def get(self, segment_id: str) -> ExtractionSegment | None: ...
    def list_for_artifact(self, artifact_id: str, limit: int | None = None) -> list[ExtractionSegment]: ...
    def list_for_extraction(self, extraction_id: str, limit: int | None = None) -> list[ExtractionSegment]: ...


class ExtractionComparisonRepository(Protocol):
    def add(self, comparison: ExtractionComparison) -> None: ...
    def get(self, comparison_id: str) -> ExtractionComparison | None: ...
    def find(self, baseline_extraction_id: str, candidate_extraction_id: str) -> ExtractionComparison | None: ...
    def list_for_extraction(self, extraction_id: str, limit: int | None = None) -> list[ExtractionComparison]: ...


class ExtractionDiffRepository(Protocol):
    def add(self, diff: ExtractionDiff) -> None: ...
    def get(self, diff_id: str) -> ExtractionDiff | None: ...
    def list_for_comparison(self, comparison_id: str, limit: int | None = None) -> list[ExtractionDiff]: ...


class ExtractionDiffEntryRepository(Protocol):
    def add(self, entry: ExtractionDiffEntry) -> None: ...
    def list_for_diff(self, diff_id: str, limit: int | None = None) -> list[ExtractionDiffEntry]: ...
