from typing import Protocol

from packages.domain.source.jurisdiction import Jurisdiction


class JurisdictionRepository(Protocol):
    def add(self, jurisdiction: Jurisdiction) -> None: ...
    def get(self, jurisdiction_id: str) -> Jurisdiction | None: ...
    def get_by_code(self, code: str) -> Jurisdiction | None: ...
    def list_children(self, parent_id: str) -> list[Jurisdiction]: ...
