from typing import Protocol

from packages.domain.source.regulatory_domain import RegulatoryDomain


class RegulatoryDomainRepository(Protocol):
    def add(self, domain: RegulatoryDomain) -> None: ...
    def get(self, domain_id: str) -> RegulatoryDomain | None: ...
    def get_by_code(self, code: str) -> RegulatoryDomain | None: ...
    def list_children(self, parent_id: str) -> list[RegulatoryDomain]: ...
